title: "Purr"
highlighter: rouge
markdown: kramdown

plugins:
  - jekyll-redirect-from

navigation:
  - text: Source Code
    url: https://github.com/origamitower/purr
    group: external

  - text: Twitter
    url: https://twitter.com/OrigamiTower
    group: external

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      group: blog
      permalink: /articles/:year/:month/:title/